// The plugin's words in Russian (owner 2026-10-06: «make 2 versions, Russian and English, switchable in settings»). The code writes the
// English text, this file gives the Russian; Hyimg's board picks by its language setting (HY.lang). Every key goes to the board under
// the prefix «frames::», so a word of this plugin never changes the same English word elsewhere on the board. en: only plural forms.
// A Hyimg without HY.t (older than 2026-10-06) shows the English.
const P = "frames::";
const RU = {
  // «Clear all» (owner 2026-10-07): the Raw Editor panel's menu and the image studio's master rows
  "Clear all": "Очистить все",
  // the image studio, 2026-10-07: the base layer (editor/basework.js), ⌘ picks a layer (pickwork.js), copy and paste on the rows (menus.js)
  "Base layer: only hide": "Базовый слой: только скрыть",
  "⌘ drags the layer under the pointer": "⌘ тянет слой под курсором",
  "⌘ picks the layer under the pointer": "⌘ выбирает слой под курсором",
  "⌘ moves without Auto-Select": "⌘ двигает без автовыбора",
  "No Raw Editor copied yet": "Raw Editor еще не скопирован",
  "Nothing applied to copy": "Копировать нечего, ничего не применено",
  "The master Raw Editor back to neutral and the master Mask to white, one step": "Мастер Raw Editor в нейтраль и мастер-маска в белое, одним шагом",
  // the grade is «Raw Editor» in both languages, the panel and the kind in «Copy properties ›» alike, as Russian Photoshop keeps «Camera
  // Raw» (owner 2026-10-06, it was «Цветокор» there and «Цветокоррекция» here: one word now, no «props::» context needed)
  "Raw Editor only on images, frames and 3D cards": "Raw Editor только у картинок, фреймов и 3D-карточек",
  // grey items of the board's menu say why (owner 2026-10-06)
  "Raw Editor isn't applied": "Raw Editor не применен",
  "This picture has no mask": "У этой картинки нет маски",
  "Select one frame": "Выдели один фрейм",
  "Only for a frame": "Только для фрейма",
  "This is already a frame": "Это уже фрейм",
  "Only images go into a frame": "Во фрейм идут только картинки",
  "Frame each": "Каждый в свой фрейм",
  "Only for 2 images or more": "Только для 2 картинок и больше",
  "This file has no transparency": "В этом файле нет прозрачности",
  "No mask here": "Маски нет",
  // the HTML frame (canvas.js)
  "Phone": "Телефон",
  "Tablet": "Планшет",
  "Laptop": "Ноутбук",
  "Desktop": "Десктоп",
  "browser": "браузер",
  "Still not made: {e}": "снимок не сделан: {e}",
  "HTML: page width": "HTML: ширина страницы",
  "Page still not made: {e}": "Снимок страницы не сделан: {e}",
  "Page size in CSS pixels: type a number or drag the frame's edge": "Размер страницы в css-пикселях: впиши число или тяни край рамки",
  "Page width": "Ширина страницы",
  "Page height": "Высота страницы",
  "The engine changes for the whole app: ⚙ › Engine": "Движок меняется для всего приложения: ⚙ › Движок",
  "Reload page · ⌘R in the frame": "Обновить страницу · ⌘R в фрейме",
  "Reload": "Обновить",
  "Open page in a new tab": "Открыть страницу в новой вкладке",
  "Open": "Открыть",
  "Done · Esc": "Готово · Esc",
  "Done": "Готово",
  "Frame {stamp}": "Фрейм {stamp}",
  "New frame": "Новый фрейм",
  "File {src} in the project folder. An agent or you write it, the canvas shows it live on a double-click.": "Файл {src} в папке проекта. Его пишет агент или ты, холст показывает его живым по двойному клику.",
  "Frame not created: {e}": "Фрейм не создан: {e}",
  "HTML frame": "HTML-фрейм",
  "still…": "снимок…",
  "Double-click: the live page · its edges resize it": "Двойной клик: живая страница · края меняют ее размер",
  "Double-click: Dev Studio · the live page on the bar over it": "Двойной клик: Dev Studio · живая страница на плашке над фреймом",
  "Live view": "Живой просмотр",
  "The live page: device sizes, the frame's edges resize it": "Живая страница: размеры устройств, края рамки меняют ее размер",
  "HTML frame: a live page on the canvas, double-click to scroll and click": "HTML-фрейм: живая страница на холсте, двойной клик, чтобы листать и нажимать",
  // the image frame (imgframe.js)
  "{n} images": ["{n} картинка", "{n} картинки", "{n} картинок"],
  "{n} frames": ["{n} фрейм", "{n} фрейма", "{n} фреймов"],
  "Frame {n}": "Фрейм {n}",
  "Frame": "Фрейм",
  "no image": "нет картинки",
  "Select images or a group with images to make a frame of": "Выдели картинки или группу с картинками, из которых сделать фрейм",
  "Only images go into a frame: deselect the rest": "Во фрейм идут только картинки: сними выделение с остального",
  "Frame reduced to 8000 px: the images lie far apart": "Фрейм уменьшен до 8000 px: картинки лежат далеко друг от друга",
  "{frames}: each image in its own, double-click opens Image Studio": "{frames}: каждая картинка в своем, двойной клик открывает Image Studio",
  "Frame: {pics} inside, double-click opens Image Studio": "Фрейм: {pics} внутри, двойной клик открывает Image Studio",
  "Frame not made: {e}": "Фрейм не сделан: {e}",
  "Opening Image Studio": "Открываю Image Studio",
  "Frame not read: {e}": "Фрейм не прочитан: {e}",
  "The frame has no images from the library": "Во фрейме нет картинок из библиотеки",
  "Unframed: {pics} back on the board": "Фрейм разобран: {pics} снова на доске",
  "Image Studio": "Image Studio",
  "“{name}” saved: {size}": "«{name}» сохранен: {size}",
  ", version {v}": ", версия {v}",
  " · version {v}": " · версия {v}",
  "Copy: this frame is already on the board": "Копия: этот фрейм уже есть на доске",
  "Frame · {size} px": "Фрейм · {size} px",
  "Open in Image Studio · Enter": "Открыть в Image Studio · Enter",
  "Make frame": "В один фрейм",
  "All {pics} in one frame · ⌥⌘G": "Все {pics} в один фрейм · ⌥⌘G",
  "Frame each ({n})": "Каждый в свой фрейм ({n})",
  "Each image in its own frame, in its place · ⌥⇧⌘G": "Каждая картинка в свой фрейм, на ее месте · ⌥⇧⌘G",
  "Open in Image Studio": "Открыть в Image Studio",
  "Unframe": "Разобрать фрейм",
  // the board's mode switch (imgframe.js, owner 2026-10-06): the short label, the studio's name (owner 2026-10-08: Image Studio)
  "Image": "Картинка",
  "Image Studio for the selected frame or image": "Image Studio для выбранного фрейма или картинки",
  "Select one image or frame: Image Studio opens for it": "Выбери одну картинку или фрейм: для них откроется Image Studio",
  "Double-click or Enter: Image Studio · the images inside never change": "Двойной клик или Enter: Image Studio · картинки внутри не меняются",
  // the colour grade of any picture (grade.js, owner 2026-10-06)
  "Raw Editor": "Raw Editor",
  "Raw Editor · click to change": "Raw Editor · клик, чтобы изменить",
  "Raw Editor did not load: {e}": "Raw Editor не загрузился: {e}",
  "Close · Esc": "Закрыть · Esc",
  "Close": "Закрыть",
  "Raw Editor on {n} images": ["Raw Editor на {n} картинке", "Raw Editor на {n} картинках", "Raw Editor на {n} картинках"],
  "Raw Editor copied": "Raw Editor скопирован",
  "Raw Editor pasted": "Raw Editor вставлен",
  "Raw Editor pasted on {n} images": ["Raw Editor вставлен на {n} картинку", "Raw Editor вставлен на {n} картинки", "Raw Editor вставлен на {n} картинок"],
  "Raw Editor on the {n} images": ["Raw Editor на {n} картинке", "Raw Editor на {n} картинках", "Raw Editor на {n} картинках"],
  "Raw Editor: the picture's file never changes": "Raw Editor: файл картинки не меняется",
  "Copy Raw Editor": "Скопировать Raw Editor",
  "Paste Raw Editor": "Вставить Raw Editor",
  "Paste Raw Editor ({n})": "Вставить Raw Editor ({n})",
  // the eyes of the grading panel: the whole grade and each section off and on, the values kept (owner 2026-10-06)
  "Turn off": "Выключить",
  "Turn on": "Включить",
  // Raw Editor's panel (editor/colorgrade.js) in Russian, Camera Raw's and Lightroom's Russian words (owner 2026-10-07: «Basic», «Tone» …
  // stayed English in the Russian panel); its title stays «Raw Editor»
  "Basic": "Основные",
  "White Balance": "Баланс белого",
  "Temp": "Температура",
  "Tint": "Оттенок",
  "Tone": "Тон",
  "Exposure": "Экспозиция",
  "Contrast": "Контраст",
  "Highlights": "Света",
  "Shadows": "Тени",
  "Whites": "Белые",
  "Blacks": "Черные",
  "Presence": "Присутствие",
  "Texture": "Текстура",
  "Clarity": "Четкость",
  "Dehaze": "Удаление дымки",
  "Vibrance": "Красочность",
  "Curve": "Кривая",
  "Parametric": "Параметрическая",
  // shorter words for a row of options with no room for the full one (colorgrade.js Ls; English keeps the full word)
  "short::Hue": "Тон",
  "RGB": "RGB",
  "Red": "Красный",
  "Green": "Зеленый",
  "Blue": "Синий",
  "Lights": "Светлые",
  "Darks": "Темные",
  "Region splits (double-click to reset)": "Границы зон (двойной клик сбрасывает)",
  "Click to add a point, drag it off the grid to remove": "Клик добавляет точку, увод за сетку убирает ее",
  "Release to remove point": "Отпусти, и точка исчезнет",
  "Input": "Вход",
  "Output": "Выход",
  "Detail": "Детализация",
  "Sharpening": "Резкость",
  "Radius": "Радиус",
  "Noise Reduction": "Шумоподавление",
  "Color Mixer": "Смешение цветов",
  "Luminance": "Светимость",
  "All": "Все",
  "Oranges": "Оранжевые",
  "Aquas": "Бирюзовые",
  "Purples": "Фиолетовые",
  "Color Grading": "Цветовые круги",
  "3-Way": "3 зоны",
  "Midtones": "Средние",
  "Global": "Общий",
  "Blending": "Смешивание",
  "Balance": "Баланс",
  "Drag to set hue and saturation (Shift keeps hue, double-click resets)": "Тяни, чтобы задать тон и насыщенность (Shift держит тон, двойной клик сбрасывает)",
  "Effects": "Эффекты",
  "Vignette": "Виньетка",
  "Amount": "Эффект",
  "Midpoint": "Средняя точка",
  "Roundness": "Округлость",
  "Feather": "Растушевка",
  "Grain": "Зерно",
  "Size": "Размер",
  "Roughness": "Неровность",
  "Presets": "Пресеты",   // as the board says it (Hyimg ui/lang-board.js)
  "Reset all": "Сбросить все",
  "Reset": "Сбросить",
  "Type a value: 10 sets it; +10 adds, -10 takes away, +10% adds a tenth, *2, /2; 1239+10 works too; an exact negative: 0-10":
    "Впиши значение: 10 ставит его; +10 прибавляет, -10 отнимает, +10% прибавляет десятую часть, *2, /2; 1239+10 тоже работает; точное отрицательное: 0-10",
  "Neutral": "Нейтральный",
  "Warm Product": "Теплый предмет",
  "Cool Studio": "Холодная студия",
  "High Contrast B&W": "Контрастный ч/б",
  "Soft Matte": "Мягкий матовый",
  "Punchy": "Сочный",
  // Hue/Saturation in the grading panel (editor/colorgrade.js, owner 2026-10-06): Photoshop's Russian names
  "Hue/Saturation": "Тон и насыщенность",   // short enough for the section title at the panel's width (owner 2026-10-07)
  "Preset": "Набор",
  "Default": "По умолчанию",
  "Custom": "Заказной",
  "Cyanotype": "Цианотипия",
  "Increase Saturation": "Увеличение насыщенности",
  "Further Increase Saturation": "Дальнейшее увеличение насыщенности",
  "Strong Saturation": "Сильная насыщенность",
  "Old Style": "Старый стиль",
  "Red Boost": "Усиление красного",
  "Sepia": "Сепия",
  "Yellow Boost": "Усиление желтого",
  "Master": "Все",
  "Reds": "Красные",
  "Yellows": "Желтые",
  "Greens": "Зеленые",
  "Cyans": "Голубые",
  "Blues": "Синие",
  "Magentas": "Пурпурные",
  "Hue": "Цветовой тон",
  "Saturation": "Насыщенность",
  "Lightness": "Яркость",
  "Colorize": "Тонирование",
  "Select a colour range on the image": "Выбрать цветовой диапазон на картинке",
  "Add to the colour range": "Добавить к диапазону",
  "Subtract from the colour range": "Вычесть из диапазона",
  "Drag the marks: between the inner ones the full effect, out to the outer ones it fades; double-click puts the range back":
    "Тяни метки: между внутренними полный эффект, к внешним он затухает; двойной клик возвращает диапазон",
  "Click a colour on the image · Esc cancels": "Кликни по цвету на картинке · Esc отменяет",
  // Selective Color in the grading panel (editor/selcolor.js, owner 2026-10-07), Photoshop's Russian names; Reds … Magentas, Whites,
  // Blacks and Black are above
  "Selective Color": "Выборочная коррекция цвета",
  "short::Selective Color": "Выборочный цвет",   // the section's title at the panel's width (the full name did not fit), the full one in its tooltip
  "Neutrals": "Нейтральные",
  "Cyan": "Голубой",
  "Magenta": "Пурпурный",
  "Yellow": "Желтый",
  "Relative": "Относительно",
  "Absolute": "Абсолютно",
  // the master mask of a picture or a frame (mask.js, owner 2026-10-06)
  "Mask": "Маска",
  "Copy mask": "Скопировать маску",
  "Paste mask": "Вставить маску",
  "Paste mask ({n})": "Вставить маску ({n})",
  "Mask from alpha": "Маска из альфа-канала",
  "Clear mask": "Убрать маску",
  "Clear mask ({n})": "Убрать маску ({n})",
  "Mask copied": "Маска скопирована",
  "Mask not copied: {e}": "Маска не скопирована: {e}",
  "Mask pasted": "Маска вставлена",
  "Mask pasted on {n} images": ["Маска вставлена на {n} картинку", "Маска вставлена на {n} картинки", "Маска вставлена на {n} картинок"],
  "Mask cleared": "Маска убрана",
  "Mask cleared on {n} images": ["Маска убрана с {n} картинки", "Маска убрана с {n} картинок", "Маска убрана с {n} картинок"],
  "Mask from alpha on {n} images": ["Маска из альфа-канала на {n} картинке", "Маска из альфа-канала на {n} картинках", "Маска из альфа-канала на {n} картинках"],
  "The image has no transparent pixels": "В картинке нет прозрачных пикселей",
  "These images have no transparent pixels": "В этих картинках нет прозрачных пикселей",
  "A mask only on images and frames": "Маска только на картинках и фреймах",
  // the image studio's tool hints in its options bar (editor/index.html T.selectHint, T.handHint through trF; owner 2026-10-07)
  "A click picks the layer under the pointer, ⇧ adds or removes it": "Клик выбирает слой под курсором, ⇧ добавляет или убирает его",
  "Drag the canvas; pinch or ⌘ with the wheel zooms": "Тяни холст, щипок или ⌘ с колесом меняют масштаб",
  // the board's dock while the studio is open (imgframe.js editorDock)
  "Fit on screen · ⌘0": "Вписать в экран · ⌘0",
  "Actions · ⌘K": "Действия · ⌘K",
  // the studio's tools in the dock (studiodock.js, editor/dockwork.js; owner 2026-10-08, round 11 D3)
  "Select and move": "Выбор и перемещение",
  "hold and drag up for the others": "зажми и веди вверх: остальные",
  "Hold, or click here: the other tools": "Зажми или нажми здесь: остальные инструменты",
  "Colors": "Цвета",
  "X swaps, D resets": "X меняет местами, D сбрасывает",
  // the whole image studio (editor/index.html, its table T through i18n.js hyEdTr; owner 2026-10-07: «the rest of the image studio being
  // English in Russian mode»): Photoshop's Russian names where they exist, the board's words where the board has them (Прозрачность,
  // Отмена, Сохранить); a function's key is its English with its parameters' names, a list of 3 forms is picked by the number
  "Double-click to zoom to this frame": "Двойной клик приближает к этому фрейму",
  "Open a Single Frame": "Открыть один фрейм",
  "Shared adjustments apply to this frame; click to exclude it": "Общие коррекции действуют на этот фрейм, клик исключает его",
  "The shared adjustments above the frames apply to this frame.": "Общие коррекции над фреймами действуют на этот фрейм",
  "Excluded: the shared adjustments leave this frame as it is.": "Исключен: общие коррекции не меняют этот фрейм",
  "Adjustment layers above this group apply to every included frame at once.": "Корректирующие слои над этой группой действуют сразу на все включенные фреймы",
  "Each frame keeps its own size; Save renders every frame.": "У каждого фрейма свой размер, «Сохранить» рендерит все фреймы",
  "excluded": "исключен",
  "Frames stay as they are; edit the layers inside them": "Фреймы остаются как есть, правь слои внутри них",
  "Original is locked: the source picture never changes": "Оригинал заблокирован: исходная картинка не меняется",
  "Originals stay in the frame; hide them instead": "Оригиналы остаются во фрейме, их можно скрыть",
  "Original is locked · painting on a new layer": "Оригинал заблокирован · рисую на новом слое",
  "Merged into a new layer, the originals are kept hidden": "Сведено в новый слой, оригиналы скрыты и сохранены",
  "Snapshots": "Снимки",
  "New snapshot of the current state": "Новый снимок текущего состояния",
  "Save as snapshot": "Сохранить как снимок",
  "Current state": "Текущее состояние",
  "OK": "ОК",
  "Cancel": "Отмена",
  "Save": "Сохранить",
  "Delete": "Удалить",
  "soon": "скоро",
  "Recent": "Недавние",
  "Tools": "Инструменты",
  "Panels": "Панели",
  "Home": "Главная",
  "Where you are": "Где ты",
  "Library": "Библиотека",
  "<b>Drag</b> onto the canvas or <b>click</b> to add a layer": "<b>Перетащи</b> на холст или <b>кликни</b>, чтобы добавить слой",
  "Render the frame onto the board and close": "Отрендерить фрейм на доску и закрыть",
  "Close without saving": "Закрыть без сохранения",
  "Settings": "Настройки",
  "Closed without saving": "Закрыто без сохранения",
  "Rename": "Переименовать",
  "Document Size": "Размер документа",
  "Reveal on Board": "Показать на доске",
  "Your changes are lost if you leave without saving.": "Изменения пропадут, если выйти без сохранения",
  "Don't Save": "Не сохранять",
  "Close without saving?": "Закрыть без сохранения?",
  "The changes made since the last save will be lost.": "Изменения после последнего сохранения пропадут",
  "Discard": "Сбросить",
  "Paper": "Бумага",
  "Graphite": "Графит",
  "Black": "Черный",
  "Slate": "Сланец",
  "Interface": "Интерфейс",
  "Shortcuts in tooltips": "Клавиши в подсказках",
  "Follows the board's <b>Paper</b> setting": "Как в настройке доски <b>Бумага</b>",
  "Actions": "Действия",
  "Actions: every command, searchable": "Действия: все команды с поиском",
  "Zoom of the document, click to fit": "Масштаб документа, клик вписывает",
  "Search actions, tools, panels": "Искать действия, инструменты, панели",
  "Nothing found": "Ничего не найдено",
  "Edit": "Редактирование",
  "Layer": "Слой",
  "Select": "Выделение",
  "Filter": "Фильтр",
  "View": "Просмотр",
  "Undo": "Отменить",
  "Redo": "Вернуть",
  "Free Transform": "Свободное трансформирование",
  "Content-Aware Fill": "Заливка с учетом содержимого",
  "Canvas Size": "Размер холста",
  "Image Size": "Размер изображения",
  "Image Rotation": "Вращение изображения",
  "180°": "180°",
  "90° Clockwise": "90° по часовой",
  "90° Counter Clockwise": "90° против часовой",
  "Flip Canvas Horizontal": "Отразить холст по горизонтали",
  "Flip Canvas Vertical": "Отразить холст по вертикали",
  "Crop to Selection": "Кадрировать по выделению",
  "Trim Transparent Pixels": "Обрезать прозрачные пиксели",
  "Anchor": "Привязка",
  "New Layer": "Новый слой",
  "New Group": "Новая группа",
  "Duplicate Layer": "Дублировать слой",
  "Delete Layer": "Удалить слой",
  "Layer Mask": "Слой-маска",
  "Reveal All": "Показать все",
  "Reveal Selection": "Показать выделенную область",
  "Disable": "Выключить",
  "Enable": "Включить",
  "New Adjustment Layer": "Новый корректирующий слой",
  "New Generative Layer": "Новый генеративный слой",
  "Create Clipping Mask": "Создать обтравочную маску",
  "Release Clipping Mask": "Отменить обтравочную маску",
  "Group Layers": "Сгруппировать слои",
  "Ungroup Layers": "Разгруппировать слои",
  "Link Layers": "Связать слои",
  "Merge Down": "Объединить с предыдущим",
  "Merge Layers": "Объединить слои",
  "Merge Visible": "Объединить видимые",
  "Merge to New Layer": "Объединить в новый слой",
  "Remove Background": "Удалить фон",
  "Deselect": "Снять выделение",
  "Inverse": "Инверсия",
  "Subject": "Предмет",
  "Modify": "Модификация",
  "Expand": "Расширить",
  "Contract": "Сжать",
  "Expand Selection": "Расширить выделение",
  "Expand by": "Расширить на",
  "Contract Selection": "Сжать выделение",
  "Contract by": "Сжать на",
  "Feather Selection": "Растушевка выделения",
  "Blur": "Размытие",
  "Gaussian Blur": "Размытие по Гауссу",
  "Only inside the selection": "Только внутри выделения",
  "On the whole layer or mask": "На весь слой или маску",
  "Sharpen": "Резкость",
  "Unsharp Mask": "Контурная резкость",
  "Zoom In": "Увеличить",
  "Zoom Out": "Уменьшить",
  "Fit on Screen": "Показать во весь экран",
  "Extras": "Вспомогательные элементы",
  "Rulers": "Линейки",
  "Grid": "Сетка",
  "Guides": "Направляющие",
  "Lock Guides": "Закрепить направляющие",
  "Snap": "Привязка",
  "New Guide": "Новая направляющая",
  "Clear Guides": "Удалить направляющие",
  "Mask Overlay": "Наложение маски",
  "Horizontal": "По горизонтали",
  "Vertical": "По вертикали",
  "Position": "Положение",
  "Extras shown": "Вспомогательные элементы видны",
  "Extras hidden, ⌘H shows them": "Вспомогательные элементы скрыты, ⌘H показывает их",
  "The overlay shows on a layer with a mask": "Наложение видно на слое с маской",
  "Select Tool": "Выбор",
  "Move Tool": "Перемещение",
  "Lasso Tool": "Лассо",
  "Rectangular Marquee Tool": "Прямоугольная область",
  "Elliptical Marquee Tool": "Овальная область",
  "Magic Wand Tool": "Волшебная палочка",
  "Brush Tool": "Кисть",
  "Spot Healing Brush Tool": "Точечная восстанавливающая кисть",
  "Eyedropper Tool": "Пипетка",
  "Hand Tool": "Рука",
  "Selection tools": "Инструменты выделения",
  "Healing tools": "Инструменты восстановления",
  "Foreground color": "Основной цвет",
  "Background color": "Цвет фона",
  "Switch colors": "Поменять цвета",
  "Default colors": "Цвета по умолчанию",
  "Black conceals": "Черный скрывает",
  "White reveals": "Белый показывает",
  "Layers": "Слои",
  "Properties": "Свойства",
  "Adjustments": "Коррекция",
  "History": "История",
  "Channels": "Каналы",
  "Generative": "Генерация",
  "Panel group menu": "Меню группы панелей",
  "Drag to change the height, past the edge to fold, double-click for halves": "Тяни, чтобы менять высоту, за край, чтобы свернуть, двойной клик делит пополам",
  "Collapse": "Свернуть",
  "double-click": "двойной клик",
  "A preset sets the <b>Raw Editor</b> on top": "Пресет ставит <b>Raw Editor</b> наверх",
  "New Raw Editor layer": "Новый слой Raw Editor",
  "No presets: the Raw Editor module is not loaded": "Пресетов нет: модуль Raw Editor не загружен",
  "Paint on the mask; ⇧-click turns it off": "Рисуй на маске, ⇧-клик выключает ее",
  "Linked with other layers": "Связан с другими слоями",
  "Generative layer": "Генеративный слой",
  "Locked, click to unlock": "Заблокирован, клик снимает блокировку",
  "Show or hide": "Показать или скрыть",
  "Blending mode": "Режим наложения",
  "Opacity": "Прозрачность",
  "Layer opacity": "Прозрачность слоя",
  "Lock": "Закрепить",
  "Locked": "Заблокирован",
  "Locked by its group": "Заблокирован группой",
  "Hidden by its group": "Скрыт группой",
  "Add a layer style": "Добавить стиль слоя",
  "Drop Shadow": "Тень",
  "Stroke": "Обводка",
  "Outer Glow": "Внешнее свечение",
  "Add layer mask": "Добавить слой-маску",
  "Normal": "Обычный",
  "Pass Through": "Пропустить",
  "Darken": "Затемнение",
  "Multiply": "Умножение",
  "Lighten": "Замена светлым",
  "Screen": "Экран",
  "Overlay": "Перекрытие",
  "Soft Light": "Мягкий свет",
  "Hard Light": "Жесткий свет",
  "Difference": "Разница",
  "Color": "Цветность",
  "Luminosity": "Яркость",
  "Transform": "Трансформирование",
  "Transforming: the fields are in the options bar": "Трансформирование: поля в панели параметров",
  "Link width and height": "Связать ширину и высоту",
  "Flip Horizontal": "Отразить по горизонтали",
  "Flip Vertical": "Отразить по вертикали",
  "off": "выкл",
  "Density": "Плотность",
  "Invert": "Инвертировать",
  "Color to Alpha": "Цвет в альфа",
  "Decontaminate Colors": "Очистить цвета",
  "The picture's background color, click to change": "Цвет фона картинки, клик меняет его",
  "From edge": "С края",
  "Take the color from the picture's edge": "Взять цвет с края картинки",
  "Group": "Группа",
  "Changes <b>every layer below</b> · clip it to limit it to one": "Меняет <b>все слои ниже</b> · обтравка ограничит одним",
  "<b>Always on top</b>: the Raw Editor the board shows and copies": "<b>Всегда сверху</b>: Raw Editor, который доска показывает и копирует",
  "The main Raw Editor and the Mask stay on top": "Главный Raw Editor и маска остаются сверху",
  "Master: the Raw Editor of the whole frame, the board shows it": "Мастер: Raw Editor всего фрейма, его показывает доска",
  "Master: the mask of the whole frame, the board shows it": "Мастер: маска всего фрейма, ее показывает доска",
  "<b>Black</b> hides, <b>white</b> shows · clips the whole frame, on the board too": "<b>Черный</b> скрывает, <b>белый</b> показывает · обрезает весь фрейм, на доске тоже",
  "Copy Mask": "Копировать маску",
  "Paste Mask": "Вставить маску",
  "Mask from Alpha": "Маска из альфа-канала",
  "Mask from Selection": "Маска из выделения",
  "Clear Mask": "Очистить маску",
  "Mask cleared: everything shows": "Маска очищена: видно все",
  "The layers have no transparent pixels": "В слоях нет прозрачных пикселей",
  "No mask copied yet": "Маска еще не скопирована",
  "Mask from the layers' alpha": "Маска из альфа-канала слоев",
  "Merge and group them from the Layer actions": "Объединить и сгруппировать можно в действиях слоя",
  "Document": "Документ",
  "Background": "Фон",
  "Transparent": "Прозрачный",
  "White": "Белый",
  "Custom color": "Свой цвет",
  "Mask inverted": "Маска инвертирована",
  "The Raw Editor module is not loaded": "Модуль Raw Editor не загружен",
  "The Raw Editor module is not loaded, the layer changes nothing yet": "Модуль Raw Editor не загружен, слой пока ничего не меняет",
  "Hardness": "Жесткость",
  "Flow": "Нажим",
  "Pen pressure controls size": "Нажим пера меняет размер",
  "New selection": "Новое выделение",
  "Add to selection": "Добавить к выделению",
  "Subtract from selection": "Вычесть из выделения",
  "Intersect with selection": "Пересечь с выделением",
  "Tolerance": "Допуск",
  "Contiguous": "Смежные пиксели",
  "Sample All Layers": "Образец со всех слоев",
  "Anti-alias": "Сглаживание",
  "Select the main subject": "Выделить главный предмет",
  "Hide the background with a mask on the selected layer": "Скрыть фон маской на выбранном слое",
  "Auto-Select": "Автовыбор",
  "Show Transform Controls": "Показать управляющие элементы",
  "Align left edges": "Выровнять левые края",
  "Align horizontal centers": "Выровнять центры по горизонтали",
  "Align right edges": "Выровнять правые края",
  "Align top edges": "Выровнять верхние края",
  "Align vertical centers": "Выровнять центры по вертикали",
  "Align bottom edges": "Выровнять нижние края",
  "Content-Aware": "С учетом содержимого",
  "Proximity Match": "Соответствие приближения",
  "Type": "Тип",
  "Point Sample": "Точка",
  "3 by 3 Average": "Среднее 3 на 3",
  "5 by 5 Average": "Среднее 5 на 5",
  "11 by 11 Average": "Среднее 11 на 11",
  "Sample Size": "Размер образца",
  "All Layers": "Все слои",
  "Current Layer": "Текущий слой",
  "Sample": "Образец",
  "Reference point: scaling and rotation go around it. ⌥-click on the canvas puts it there": "Опорная точка: вокруг нее масштаб и поворот, ⌥-клик на холсте ставит ее туда",
  "Reference point X": "Опорная точка X",
  "Reference point Y": "Опорная точка Y",
  "Width; 50%, *2, +10 work": "Ширина: работают 50%, *2, +10",
  "Height; 50%, *2, +10 work": "Высота: работают 50%, *2, +10",
  "Angle": "Угол",
  "Painting on the mask: black conceals, white reveals": "Рисую на маске: черный скрывает, белый показывает",
  "Invert mask": "Инвертировать маску",
  "Cancel the mask edit": "Отменить правку маски",
  "Apply the mask": "Применить маску",
  "Cancel transform": "Отменить трансформирование",
  "Commit transform": "Применить трансформирование",
  "Select one picture or adjustment layer": "Выдели одну картинку или корректирующий слой",
  "New mask: paint with black to conceal": "Новая маска: черный цвет скрывает",
  "Mask applied": "Маска применена",
  "Mask restored": "Маска восстановлена",
  "Transform cancelled": "Трансформирование отменено",
  "Transform applied": "Трансформирование применено",
  "This works when Image Studio is open in Hyimg": "Это работает, когда Image Studio открыта в Hyimg",
  " piece": " фрагмент",
  "The layer position is locked": "Положение слоя заблокировано",
  "Select a layer": "Выбери слой",
  "Select one layer": "Выбери один слой",
  "Nothing to undo": "Нечего отменять",
  "Undo ": "Отменено: ",
  "Nothing to redo": "Нечего возвращать",
  "Redo ": "Возвращено: ",
  "The brush paints on a picture layer or a mask": "Кисть рисует на слое с картинкой или на маске",
  "The layer is hidden": "Слой скрыт",
  "The layer pixels are locked": "Пиксели слоя заблокированы",
  "Layer ": "Слой ",
  "Group ": "Группа ",
  " copy": " копия",
  "No layers selected": "Слои не выбраны",
  "Layer duplicated": "Слой продублирован",
  "There is no layer below": "Ниже нет слоя",
  "Merged down": "Объединено с предыдущим",
  "Merged": "Объединенный",
  "Visible layers merged": "Видимые слои объединены",
  "Merged from ": "Объединено из ",
  " layers": " слоев",
  "A new layer from the selected layers": "Новый слой из выбранных слоев",
  "There is no layer below to clip to": "Ниже нет слоя для обтравки",
  "Clipping released": "Обтравка снята",
  "Layers grouped": "Слои сгруппированы",
  "Select a group": "Выбери группу",
  "A mask goes on a picture or adjustment layer": "Маска ставится на картинку или корректирующий слой",
  "The mask is there and selected": "Маска уже есть и выбрана",
  "Mask from the selection": "Маска из выделения",
  "Mask added, paint with black to conceal": "Маска добавлена, черный цвет скрывает",
  "Select two layers or more": "Выбери 2 слоя или больше",
  "Layers unlinked": "Связь слоев снята",
  "Layers linked, they move together": "Слои связаны и двигаются вместе",
  "Raw Editor layer": "Слой Raw Editor",
  "Select a picture layer": "Выбери слой с картинкой",
  "Selection copied to a new layer": "Выделение скопировано на новый слой",
  "No selection": "Нет выделения",
  "No transparent edges": "Нет прозрачных краев",
  "Select a layer or turn on Sample All Layers": "Выбери слой или включи «Образец со всех слоев»",
  "Server error": "Ошибка сервера",
  "The server did not answer in 90 seconds": "Сервер не ответил за 90 секунд",
  "The server did not return a picture": "Сервер не вернул картинку",
  "Finding the subject…": "Ищу предмет…",
  "Subject selected without the neural network": "Предмет выделен без нейросети",
  "Subject selected": "Предмет выделен",
  "Failed: ": "Не вышло: ",
  "Separating the subject from the background…": "Отделяю предмет от фона…",
  "Background removed, edges decontaminated": "Фон удален, края очищены",
  "Background removed without the neural network": "Фон удален без нейросети",
  "Wait, a fill is still running": "Подожди, заливка еще идет",
  "Select an area first": "Сначала выдели область",
  "Fill without the neural network": "Заливка без нейросети",
  "Filling…": "Заливаю…",
  "Fill failed: ": "Заливка не вышла: ",
  "Spot Healing ": "Восстановление ",
  "Content-Aware Fill ": "Заливка с учетом содержимого ",
  "Healed": "Восстановлено",
  "Wait, a generation is still running": "Подожди, генерация еще идет",
  "Select an area or a layer with a mask": "Выдели область или слой с маской",
  "Generative ": "Генерация ",
  "Generated, pick a variation": "Готово, выбери вариант",
  "Generation failed: ": "Генерация не вышла: ",
  "Describe what to generate (optional)": "Опиши, что сгенерировать (необязательно)",
  "The description is not used yet: it fills <b>from the surroundings</b>": "Описание пока не используется: заливка берется <b>из окружения</b>",
  "Fills the selected area as a new layer with three variations": "Заливает выделенную область новым слоем с 3 вариантами",
  "Fills the mask area of the selected layer": "Заливает область маски выбранного слоя",
  "Generate": "Сгенерировать",
  "Variations": "Варианты",
  "Guides are locked": "Направляющие закреплены",
  "Guides unlocked": "Направляющие откреплены",
  "Guide deleted": "Направляющая удалена",
  "Snap on": "Привязка включена",
  "Snap off": "Привязка выключена",
  "Guides shown": "Направляющие видны",
  "Guides hidden": "Направляющие скрыты",
  "Color picked: ": "Цвет взят: ",
  "Picture": "Картинка",
  "Rendering the frame": "Рендерю фрейм",
  "A number sets the value; +10 adds, -10 takes away, +10% adds a tenth, *2, /2, 1239+10": "Число задает значение: +10 прибавляет, -10 отнимает, +10% прибавляет десятую часть, *2, /2, 1239+10",
  "A number sets the value; +10 adds, -10 takes away, +10%, *2, /2; an exact negative: 0-10": "Число задает значение: +10 прибавляет, -10 отнимает, +10%, *2, /2, точное отрицательное: 0-10",
  "Opening the frame…": "Открываю фрейм…",
  "The layers are still loading": "Слои еще загружаются",
  "Loading the layers…": "Загружаю слои…",
  "The frame did not open: ": "Фрейм не открылся: ",
  "Saving the frame": "Сохраняю фрейм",
  "Not saved: ": "Не сохранено: ",
  "Wait, the frame is being saved": "Подожди, фрейм сохраняется",
  "Brush Tool (Mask)": "Кисть (маска)",
  "Add Layer Mask": "Добавить слой-маску",
  "Unlink Layers": "Отменить связь слоев",
  "New Raw Editor Layer": "Новый слой Raw Editor",
  "Clear": "Очистить",
  "Layer Via Copy": "Скопировать на новый слой",
  "Rotate Canvas": "Повернуть холст",
  "Flip Canvas": "Отразить холст",
  "Crop": "Кадрирование",
  "Spot Healing Brush": "Точечная восстанавливающая кисть",
  "Generative Variation": "Генеративный вариант",
  "Move": "Перемещение",
  "Nudge": "Сдвиг",
  "Place": "Поместить",
  "Hide Layer": "Скрыть слой",
  "Show Layer": "Показать слой",
  "Unlock Layer": "Снять блокировку слоя",
  "Disable Layer Mask": "Выключить слой-маску",
  "Layer Order": "Порядок слоев",
  "Rename Layer": "Переименовать слой",
  "Blending Change": "Смена режима наложения",
  "Opacity Change": "Смена прозрачности",
  "Lock Layer": "Заблокировать слой",
  "Resize": "Изменить размер",
  "Flip Layer": "Отразить слой",
  "Mask Density": "Плотность маски",
  "Mask Feather": "Растушевка маски",
  "Invert Mask": "Инвертировать маску",
  "Background Color": "Цвет фона",
  "Document Background": "Фон документа",
  "Align": "Выравнивание",
  "Free Transform Selection": "Свободное трансформирование выделения",
  "Delete Layer Mask": "Удалить слой-маску",
  "Shared Adjustments": "Общие коррекции",
  "Snapshot": "Снимок",
  "Frames · {n}": "Фреймы · {n}",
  "Open Selection as Batch ({n} frames)": ["Открыть выделенное пакетом ({n} фрейм)", "Открыть выделенное пакетом ({n} фрейма)", "Открыть выделенное пакетом ({n} фреймов)"],
  "{n} frames rendered": ["{n} фрейм отрендерен", "{n} фрейма отрендерено", "{n} фреймов отрендерено"],
  "Snapshot {i}": "Снимок {i}",
  "Snapshot {i} saved": "Снимок {i} сохранен",
  "{n} restored": "{n}: восстановлен",
  "{n} strokes": ["{n} мазок", "{n} мазка", "{n} мазков"],
  "{n} changes": ["{n} изменение", "{n} изменения", "{n} изменений"],
  "Opens {w}": "Откроет {w}",
  "Save changes to \"{n}\"?": "Сохранить изменения в «{n}»?",
  "Now {w} × {h} px, up to {mx} px per side. Layers scale with the document": "Сейчас {w} × {h} px, до {mx} px по стороне, слои масштабируются с документом",
  "Now {w} × {h} px, up to {mx} px per side": "Сейчас {w} × {h} px, до {mx} px по стороне",
  "Raw Editor: {n}": "Raw Editor: {n}",
  "{n} steps": ["{n} шаг", "{n} шага", "{n} шагов"],
  "{n} Mask": "Маска {n}",
  "{c} layers inside": ["{c} слой внутри", "{c} слоя внутри", "{c} слоев внутри"],
  "{n} layers": ["{n} слой", "{n} слоя", "{n} слоев"],
  "The frame's own size, up to {mx} px per side. Zoom is measured against it.": "Собственный размер фрейма, до {mx} px по стороне, масштаб считается от него",
  "Preset {i}": "Пресет {i}",
  "{n} layers duplicated": ["{n} слой продублирован", "{n} слоя продублировано", "{n} слоев продублировано"],
  "{n} layers merged": ["{n} слой объединен", "{n} слоя объединено", "{n} слоев объединено"],
  "\"{a}\" clipped to \"{b}\"": "«{a}» обтравлен по «{b}»",
  "Gaussian Blur: {r} px": "Размытие по Гауссу: {r} px",
  "Canvas {w} × {h} px": "Холст {w} × {h} px",
  "Image {w} × {h} px": "Изображение {w} × {h} px",
  "Cropped to {w} × {h} px": "Кадрировано до {w} × {h} px",
  "Generating {i} of 3": "Генерирую {i} из 3",
  "Variation {i}": "Вариант {i}",
  "Placed: {n}": "Помещено: {n}",
  "Frame rendered: {w} × {h} px": "Фрейм отрендерен: {w} × {h} px",
  "Source picture missing: {p}": "Нет исходной картинки: {p}",
  "Frame saved: {w} × {h} px": "Фрейм сохранен: {w} × {h} px",
  // masks, selections, the right click and the clipboard the Photoshop way (owner 2026-10-07, editor/maskwork.js, clipwork.js, selwork.js, menus.js)
  "Contract/Expand": "Сжать/расширить",
  "Smooth": "Сгладить",
  "Mask Contract/Expand": "Сжатие/расширение маски",
  "Mask Smooth": "Сглаживание маски",
  "How the mask shows": "Как видна маска",
  "Red Overlay": "Красным",
  "On Black": "На черном",
  "On White": "На белом",
  "Black & White": "Черно-белая",
  "Off": "Выкл",
  "Apply": "Применить",
  "Apply the mask and leave it": "Применить маску и выйти из нее",
  "Editing the mask: black hides, white shows": "Правка маски: черное скрывает, белое показывает",
  "Copied": "Скопировано",
  "Raw Editor settings copied": "Настройки Raw Editor скопированы",
  "Pasted into the mask": "Вставлено в маску",
  "Pasted as a new layer": "Вставлено новым слоем",
  "Raw Editor settings pasted": "Настройки Raw Editor вставлены",
  "Nothing copied yet": "Пока ничего не скопировано",
  "No properties copied yet": "Свойства еще не скопированы",
  "Properties pasted": "Свойства вставлены",
  "These properties don't apply here": "Эти свойства сюда не подходят",
  "Paste": "Вставить",
  "Paste Layer Mask": "Вставить слой-маску",
  "Paste Properties": "Вставить свойства",
  "Move Layer Mask": "Перенести слой-маску",
  "Copy Layer Mask": "Копировать слой-маску",
  "Mask moved": "Маска перенесена",
  "Mask copied to the layer": "Маска скопирована на слой",
  "Mask pasted on {n} layers": ["Маска вставлена на {n} слой", "Маска вставлена на {n} слоя", "Маска вставлена на {n} слоев"],
  "The mask alone · ⌥-click its thumbnail to go back": "Только маска · ⌥-клик по миниатюре вернет вид",
  "Reselect": "Выделить снова",
  "Layer Via Cut": "Вырезать на новый слой",
  "Selection cut to a new layer": "Выделенное вырезано на новый слой",
  "Fill": "Заливка",
  "Foreground Color": "Основной цвет",
  "50% Gray": "50% серого",
  "Filled": "Залито",
  "Master layers": "Мастер-слои",
  "Master layers act on the whole frame, the board shows them; they stay on top": "Мастер-слои действуют на весь фрейм, их показывает доска, они всегда сверху",
  "Select Inverse": "Инверсия выделения",
  "Flatten Image": "Выполнить сведение",
  "Apply Layer Mask": "Применить слой-маску",
  "Copy Mask as Image": "Копировать маску картинкой",
  "Paste Into Mask": "Вставить в маску",
  "Delete from Mask": "Удалить из маски",
  "Enable Layer Mask": "Включить слой-маску",
  "Show the Mask Alone": "Показать только маску",
  "Copy Layer Style": "Скопировать стиль слоя",
  "Paste Layer Style": "Вставить стиль слоя",
  "Layer styles are not there yet": "Стилей слоя пока нет",
  "Layers Here": "Слои здесь",
  "No layer under the pointer": "Под курсором нет слоя",
  "Layer Color": "Цвет слоя",
  "A master layer stays on top and acts on the whole frame": "Мастер-слой всегда сверху и действует на весь фрейм",
  "The master Mask is the frame's mask": "Мастер-маска: маска всего фрейма",
  "This layer has no mask": "У слоя нет маски",
  "This layer has a mask": "У слоя уже есть маска",
  "Only with a selection": "Только с выделением",
  "Target a mask first: click its thumbnail": "Сначала выбери маску: клик по ее миниатюре",
  "Only for a picture layer": "Только для слоя с картинкой",
  "An adjustment layer's mask stays a mask": "Маска корректирующего слоя остается маской",
  "No selection to bring back": "Нечего выделить снова",
  "Copy": "Копировать",
  "Paste as New Layer": "Вставить новым слоем",
};
const EN = {
  "{n} images": ["{n} image", "{n} images"],
  "Mask pasted on {n} images": ["Mask pasted on {n} image", "Mask pasted on {n} images"],
  "Mask cleared on {n} images": ["Mask cleared on {n} image", "Mask cleared on {n} images"],
  "Mask from alpha on {n} images": ["Mask from alpha on {n} image", "Mask from alpha on {n} images"],
  "{n} frames": ["{n} frame", "{n} frames"],
};

const pre = d => Object.fromEntries(Object.entries(d).map(([k, v]) => [P + k, v]));
let added = false;
// t(key, vars) for this plugin: the board's T with the prefix, or English when the board has none
export function translator(HY) {
  if (HY.t && HY.strings) {
    if (!added) { HY.strings({ ru: pre(RU), en: pre(EN) }); added = true; }
    return (k, v) => HY.t(P + k, v);
  }
  return (k, v) => {
    let s = EN[k] !== undefined ? EN[k] : k;
    if (Array.isArray(s)) s = Number(v && v.n) === 1 ? s[0] : s[1];
    return v ? String(s).replace(/\{(\w+)\}/g, (m, x) => (x in v ? String(v[x]) : m)) : s;
  };
}
export const lang = HY => (HY.lang === "ru" ? "ru" : "en");
export { RU, EN };
